export const visibilitySections = [
  { id: "basics", title: "Public, private and published are different", paragraphs: [
    "Private is the default when the creation payload does not explicitly choose public. A private trip is excluded from normal public discovery. Its owner and qualifying participant records can still open it.",
    "Public means discoverable to signed-in users when the trip status is active. It does not mean an anonymous internet visitor can browse the public-trips API: both listing and detail routes require a valid user session.",
    "Visibility and status are separate fields. Setting a draft to public does not publish it. Drafts and other non-active trips are excluded from public discovery, but the detail route does not impose that status restriction on the owner or qualifying participants.",
    "Audience, trip type, dates, destination, saved filters and map radius help describe or filter trips. The detail access check does not use those fields as privacy permissions. Billing access is also separate from visibility.",
  ], sources: ["src/app/api/public-trips/route.ts", "src/app/api/trips/[id]/route.ts", "src/app/api/trip-organiser/finalise/route.ts"] },
  { id: "discovery", title: "What appears in Explore Public Trips", paragraphs: [
    "The normal list returns trips where status=active and visibility=public. It excludes the signed-in user’s own trips and sorts newest first. Owners should look in My Trips rather than expect their own card in Explore.",
    "A public card response includes title, destination, description, dates, cover image, status, visibility, owner ID and creation time. It also adds counts for planning options and people where available. Optional card-count failures should not prevent browsing.",
    "Card people counts include the organiser and deduplicated active travellers. The detail preview’s participantTotal instead counts active or pending participants and excludes the organiser unless present as a participant record. These two totals can differ.",
    "Search, dates, locations and saved filters narrow the returned list. An empty filtered list is not proof that the trip is private or inaccessible. Clearing a filter does not change trip visibility or membership.",
  ], sources: ["src/app/api/public-trips/route.ts", "src/app/public-trips/page.tsx", "src/lib/public-trip-filters.ts"] },
  { id: "roles", title: "How opening a trip chooses a role", paragraphs: [
    "After authentication, the detail route first checks ownership. The owner gets organiser access. Otherwise it looks up a participant record by user ID or account email and checks its statuses. If that grants access, the role is participant. Only then does it fall back to a public preview for an active public trip. If none applies it returns 403.",
    "Participant access is broader than confirmed attendance: membership_status active, pending_approval or invited qualifies; legacy status accepted, pending, linked or invited also qualifies. A membership_status of declined or removed, or a legacy status of declined, overrides those allowed states and blocks participant access.",
    "Pending applicants and invited users can therefore open private trip details before approval or acceptance. They receive the participant detail response, not the restricted public preview. This is current behaviour and should be considered before placing sensitive information in a trip.",
    "Declining or removing someone does not stop them seeing the public preview of an active public trip. Making a trip private removes that public fallback but does not remove existing qualifying participant access.",
  ], sources: ["src/app/api/trips/[id]/route.ts"] },
  { id: "data", title: "What each viewer receives", paragraphs: [
    "Organiser and participant detail responses include the trip, planning options, participant rows and reference people. The API does not limit a pending or invited participant to only their own participant row.",
    "Public preview responses still include the trip and enriched hotels, activities, transport and dining. They suppress referencePeople and the full participant list, returning only the current viewer’s participant record if one exists plus a participant total. Public is not a cover-photo-only preview: planning details returned by this endpoint are part of its disclosure.",
    "Expense access uses a separate server check: only the organiser and active travellers qualify. For expenses, membership_status takes precedence when present, with accepted used as the legacy fallback. The organiser sees trip-wide costs and payments; travellers receive their assigned payments and the associated expenses, their own shares, and receipts associated with those expenses.",
    "The trip screen shows messaging controls for the organiser or active/accepted participants when there is at least one accepted participant. This is a UI condition, not proof of every message endpoint’s authorisation. Votes, comments, files, other section endpoints and database policies have their own checks; this guide does not certify them as identical to the main detail route.",
    "Trip images are uploaded using public storage URLs. Private trip visibility should not be described as revoking a previously shared image URL. Changing visibility cannot erase data someone already viewed, saved or downloaded.",
  ], sources: ["src/app/api/trips/[id]/route.ts", "src/lib/expenses/access.ts", "src/app/api/trips/[id]/expenses/route.ts", "src/app/trips/[id]/page.tsx"] },
  { id: "joining", title: "Requests, approval and attendance", paragraphs: [
    "A signed-in non-owner can request participation only while the trip is active and public (or recognised by the seed-trip fallback). The request requires an account email and creates a traveller record with status pending and membership_status pending_approval.",
    "If a participant record already exists, the request action returns that record rather than creating or resetting it. This includes previously declined records: requesting again is not an automatic reapplication flow. The owner receives 409 if attempting to request their own trip.",
    "Only the owner can approve or decline through the normal trip update endpoint. Approval writes accepted/active; declining writes declined/declined. Older schemas fall back to the legacy status. Attendance is separate: only approved participants can update going, maybe or not_going.",
    "Setting attendance to not_going does not itself remove membership or access. Invites are matched by account identity/email, not granted to anyone who happens to possess the trip URL.",
  ], sources: ["src/app/api/trips/[id]/route.ts", "src/app/api/travellers/respond/route.ts"] },
  { id: "changes", title: "Changing visibility", paragraphs: [
    "The organiser can change visibility from the trip screen. The normal PATCH action update_visibility requires owner_id to match the signed-in user; other users receive 403. The value is normalised to public only when explicitly supplied as public, otherwise private.",
    "Private to public: an active trip becomes eligible for public discovery and preview; a draft remains excluded until active. Existing participant records are not changed.",
    "Public to private: normal discovery and public preview no longer qualify on subsequent requests. Existing invited, pending and active participant access remains. The visibility update does not revoke invitations, remove participants, or reset attendance.",
    "This route does not broadcast a visibility-specific invalidation or send a visibility-change notification. Already-open screens may retain previously fetched content until refreshed; a successful visibility update is not a recall mechanism.",
  ], sources: ["src/app/api/trips/[id]/route.ts", "src/app/trips/[id]/page.tsx"] },
  { id: "compatibility", title: "Schema fallbacks and current exceptions", paragraphs: [
    "If the public listing encounters a schema error, it falls back to active trips owned by three configured demo seed accounts and labels them public. It does not safely substitute all active trips for a missing visibility column.",
    "The detail and participation-request routes also treat active trips owned by those seed accounts as public, regardless of an explicit private value. Consequently, a seed-owned trip can allow public detail access even if the normal list excludes it. Do not use seed accounts for confidential trips.",
    "The compatibility selectors can omit unavailable metadata. The creation function includes only columns present in the database, so an old schema can fail to persist a requested visibility value. Updating visibility needs the relevant columns and can return an error rather than silently succeeding.",
    "The guide describes reviewed application code, not a live database/RLS audit. Confirm the deployed version and migrations before diagnosing production visibility. Admin backoffice access is a separate server-authorised workflow; being an admin is not a general bypass in the normal trip-detail owner/participant/public decision.",
  ], sources: ["src/app/api/public-trips/route.ts", "src/app/api/trips/[id]/route.ts", "supabase/migrations/20261002144823_enforce_single_free_trip.sql"] },
];

export const visibilityScenarios = [
  ["Signed out visitor opens a public trip", "The API requires authentication; public discovery is not anonymous."],
  ["Owner looks for their public trip in Explore", "Their own trips are excluded from that list; use My Trips."],
  ["Unconnected user opens an active public trip", "Public preview, including planning options; no full participant list."],
  ["Unconnected user opens a private trip link", "403. Possession of the URL is not a membership grant."],
  ["Unconnected user opens a public draft", "No public access because the status is not active."],
  ["Owner opens a draft or private trip", "Organiser access; public-list eligibility is irrelevant."],
  ["Invited user opens a private draft", "Qualifying invited membership/status grants participant detail access, even before acceptance."],
  ["Pending applicant opens trip details", "Participant access, not just the public preview, under the current route."],
  ["Accepted traveller opens a private trip", "Participant access remains available."],
  ["Declined or removed traveller opens a private trip", "Participant access is blocked; no public fallback, so 403."],
  ["Declined or removed traveller opens an active public trip", "Public preview can still be available; decline is not a public-view ban."],
  ["Member marks attendance as not going", "Attendance changes; membership access is not automatically revoked."],
  ["Owner makes an active private trip public", "Eligible for discovery and public preview on subsequent requests."],
  ["Owner makes a public trip private", "Unconnected viewers lose normal public access; existing qualifying members retain access."],
  ["Owner changes a draft to public", "It still needs active status to appear publicly."],
  ["Traveller tries to change visibility", "The owner-only update check returns 403."],
  ["Someone requests to join a private/non-active trip", "The participation-request endpoint returns 403, excluding the documented seed exception."],
  ["Someone requests to join an active public trip", "A pending-approval record is created if none exists; joining is not immediate approval."],
  ["Previously declined user requests again", "The existing record is returned; it is not reset to pending automatically."],
  ["Pending or invited user opens expenses", "The separate expense access check requires active membership or organiser ownership."],
  ["Active traveller opens expenses", "Only their assigned payments and associated expenses/shares are returned, including associated receipts."],
  ["Owner opens expenses", "Trip-wide expense access under the separate expense API."],
  ["Public card count differs from trip preview count", "The endpoints count different groups: card includes owner and active travellers; preview includes active and pending participant rows."],
  ["Filters hide an otherwise public trip", "Clear search/date/place/radius filters; filtering does not change permissions."],
  ["An old tab remains visible after privacy changes", "Previously loaded content can remain; subsequent API checks apply the current visibility."],
  ["A private trip image link is forwarded", "Public storage URLs do not inherit the trip’s privacy setting."],
  ["A configured demo seed owner sets a trip private", "Active seed-owned trips can still satisfy the public-detail fallback. This is a current exception."],
  ["Visibility column is missing in production", "Normal persistence/listing may differ or error; inspect schema and fallback behaviour rather than trusting a label."],
];
