export const notificationSections = [
  { id: "channels", title: "Channels and what delivery means", paragraphs: [
    "In-app notifications are rows in user_notifications, displayed in the account bell. The action dispatcher calls this channel push and uses send_push, but it inserts a database row. This repository does not implement a browser Push API/service-worker delivery system; no phone lock-screen alert is promised.",
    "Application email is handed to the configured email webhook. The intended destination is the Make webhook configured in Backoffice; the sender loads the primary email_delivery_settings row at send time rather than hardcoding that destination. Check the saved setting to confirm the live destination. This guide does not read or change live settings.",
    "Authentication emails, such as sign-up confirmation and password recovery, are handled through Supabase Auth and its email configuration. They do not pass through sendEmailWebhook or these application preferences. Stripe billing emails are also a separate provider configuration.",
    "An email marked sent here means the webhook returned an HTTP success response. It does not prove Make sent the message, the provider delivered it, or the recipient opened it. No bounce, complaint or open-tracking callback is implemented in this delivery helper.",
  ], sources: ["src/lib/notifications/dispatch.ts", "src/lib/backoffice/email-webhook.ts", "src/components/account-notifications.tsx"] },
  { id: "actions", title: "Action-based delivery and recipients", paragraphs: [
    "dispatchNotificationAction loads an enabled notification_actions entry and the trip. A missing/disabled action or missing trip stops this path before a batch is created. Recipient types select organiser, active participants, invited participants or an affected participant. The actor is excluded by matching user ID.",
    "Active membership uses membership_status when present, falling back to accepted status. Invited matching includes membership_status invited or legacy invited, linked or pending status. Affected matching uses the supplied user ID or email. Recipients are deduplicated by user ID, or email when no user ID is present; mixed ID/email duplicates are not guaranteed to collapse.",
    "The invited_participant type is not automatically restricted to the newest invite: it can match all rows meeting the invited predicate. Actor exclusion also cannot recognise an email-only row as the actor unless its user ID matches. Review actual audience evaluations before assuming a singular action name means one recipient.",
    "The dispatcher creates a batch, records candidates and selection reasons, then attempts each enabled channel subject to preferences. Chat, vote and invite-response routes call it. Merely adding an action or template in Backoffice does not wire an application event to it. Some trip routes only log notification events; a prepared log is not evidence of a sent message.",
    "Action settings control this dispatcher. Database-triggered expense, decision and reminder notifications use a separate path and do not consult notification_actions. Disabling an action is therefore not a global switch for every notification with a similar name.",
  ], sources: ["src/lib/notifications/dispatch.ts", "src/app/api/trips/[id]/discussion/route.ts", "src/app/api/trips/[id]/voting/route.ts", "src/app/api/travellers/respond/route.ts", "src/app/api/trips/[id]/route.ts"] },
  { id: "preferences", title: "Preferences and active-user suppression", paragraphs: [
    "Preferences default to enabled for in_app, email, invites, planning and payments. Users must be authenticated to read or save their own preferences. Saving requires all five boolean fields. A channel switch and a category switch both affect eligibility.",
    "The dispatcher classifies expense.* and reminder.payment* as payments, names containing invit or starting participant. as invites, and everything else as planning. Labels do not determine the category: for example payment.requested and membership.requested currently fall into planning under this naming rule.",
    "When enabled on an action, suppress_email_when_active skips immediate email for a known user seen within the configured window, defaulting to five minutes. AppShell sends presence while visible roughly every minute and when becoming visible. This is app-wide presence, not proof the user read the trip or message. Email-only recipients cannot be suppressed by a missing user ID.",
    "The immediate dispatcher records preference-disabled channels as skipped and fails a delivery if preference lookup fails. The database trigger also applies preferences: for expense.*, decision.* and reminder.* it can queue email before suppressing the in-app row. This allows email-only delivery from that path. Queued delivery checks preferences again before sending, but does not apply the action’s active-user suppression.",
  ], sources: ["src/app/api/notifications/preferences/route.ts", "src/app/api/notifications/presence/route.ts", "src/components/app-shell.tsx", "src/lib/notifications/dispatch.ts", "supabase/migrations/20260917100000_notification_preferences_reminders.sql"] },
  { id: "templates", title: "Email templates and webhook handoff", paragraphs: [
    "Immediate action email uses the linked notification rule’s subject/body where available, falling back to the action title/message. It uses a custom template when configured, otherwise the global HTML template. Supported replacement values include first_name, participant_name, trip_title, message, content, email_subject, action_url, action_label and logo_url.",
    "The dispatcher uses the action’s enabled/channel/audience settings; it does not enforce the linked rule’s enabled, audience, channel or sendTiming fields, and does not use pushBody for the in-app message. Changing those template fields alone is not a scheduler or recipient rule.",
    "Queued emails currently use the queued title/message and a simple Open Journi link, not the global/custom template pipeline. Template changes in Backoffice therefore do not style every outgoing application email.",
    "The sender POSTs JSON containing event=email.send, sentAt and an email object with to, subject, html, text and optional templateId, triggerKey and idempotencyKey. An optional stored token is sent as Bearer authorisation and encrypted at rest using EMAIL_WEBHOOK_ENCRYPTION_KEY. Secret values should never be copied into this guide.",
    "Webhook URLs require HTTPS and reject credentials in the URL and checked local/private addresses. Redirects are rejected and requests time out after 15 seconds. Missing settings, non-success responses or network errors fail the handoff. A successful test email only verifies that test path; it does not prove every event is connected.",
    "The invite-response route additionally posts a separate business-event webhook. That is not the shared email.send helper and its downstream Make behaviour is not defined in this repository. Check external automations when investigating duplicate invite emails.",
  ], sources: ["src/lib/backoffice/email-webhook.ts", "src/lib/backoffice/email-template.ts", "src/lib/backoffice/notifications.ts", "src/lib/notifications/dispatch.ts", "src/app/api/backoffice/email-webhook/send-test/route.ts", "src/app/api/travellers/respond/route.ts"] },
  { id: "expenses", title: "Expenses, decisions and reminder recipients", paragraphs: [
    "Payment database triggers create expense notifications in the same transaction as payment changes. New due payments target the assigned active traveller (or organiser if assigned to them). Paid/status changes also notify the organiser. Claiming payment or withdrawing a claim notifies the assigned person and organiser. Unchanged tracked fields produce no new notification.",
    "Payment amount, label or payer changes generate an update notification for the current payer; an update does not separately notify the old payer. Deletion uses the old payment row to notify its assigned eligible person. Removed/inactive travellers are excluded by the recipient lookup. The trigger has no actor-exclusion check, so an organiser may receive an event they caused.",
    "Decision locking/reopening and cancellation workflows insert decision.* inbox notifications, which can also queue email. Membership changes can notify the organiser to review expense splits; those records do not automatically rebalance or refund payments.",
    "Payment reminders target eligible assigned people on the day before due, the due date and three days overdue, using the database current_date. They require a due, unclaimed payment and exclude cancelled, closed or completed trips. They are not daily overdue reminders forever.",
    "Voting reminders cover active participants with an outstanding vote in a populated, undecided category when the deadline is still in the future and within 24 hours. Draft, cancelled, closed and completed trips are excluded. Reminder markers deduplicate by payment/deadline/time bucket/person or trip/voting deadline/person.",
    "The migration schedules reminder generation hourly at minute five through pg_cron. It does not itself deliver emails. The authenticated app cron endpoint also generates reminders then drains the queue; an external scheduler must call it. A missed payment-reminder date is not automatically replayed later, and changing preferences after a marker is recorded does not recreate that same reminder.",
  ], sources: ["supabase/migrations/20260917090000_trip_workflows.sql", "supabase/migrations/20260917100000_notification_preferences_reminders.sql", "src/app/api/cron/notifications/route.ts"] },
  { id: "queue", title: "Queue delivery, retries and stale reminders", paragraphs: [
    "GET /api/cron/notifications requires the configured CRON_SECRET bearer value and an HTTPS NEXT_PUBLIC_SITE_URL. It generates reminders, then claims up to 25 eligible queue rows with a ten-minute processing lease. The SQL claim increments attempts and avoids concurrent workers claiming the same eligible row.",
    "Before sending, the worker rechecks trip existence, recipient email, owner/active membership and preferences. For payment reminders it checks that the payment is still due and unclaimed and the due date is unchanged. For voting reminders it checks that the deadline is unchanged and still future. It does not recheck whether the user has since voted or the category has since been decided.",
    "No-longer-eligible messages become skipped. Reminder emails for cancelled, closed or completed trips are skipped. Delivery exceptions return to pending until five attempts have been reached, then failed. Backoff is 2^attempts minutes; expired processing leases can be reclaimed, with the fifth expired lease marked failed.",
    "Queued webhook sends include the queue ID as Idempotency-Key. The receiver must honour it to prevent duplicates if an accepted webhook response is lost or a worker stops before recording success. Immediate action emails do not supply an idempotency key and have no automatic retry loop in the dispatcher.",
    "If a dispatcher action for expense.*, decision.* or reminder.* both inserts an in-app row and sends immediate email, the database trigger may also enqueue an email. That creates a possible duplicate route. A completed batch can also contain only skips, no enabled channels or no recipients; sent_count counts channel deliveries, not unique people.",
  ], sources: ["src/app/api/cron/notifications/route.ts", "supabase/migrations/20260917100000_notification_preferences_reminders.sql", "src/lib/notifications/dispatch.ts"] },
  { id: "inbox", title: "The bell, unread counts and links", paragraphs: [
    "The bell loads the newest 50 accessible user_notifications rows and separately counts all unread rows. Database row policies scope them to the current account by ID/email. The badge displays 99+ above 99, so the unread total can exceed the visible list length.",
    "The client refreshes when opened, on window focus, when the page becomes visible, and every 30 seconds while visible. It is polling, not an instant device-push stream. Account changes clear the old list and pending responses are guarded against replacing the new account’s state.",
    "Opening an item marks it read, refreshes counts and navigates only to a same-origin HTTP(S) destination. Mark all read updates all unread rows allowed by the database policy, not only the displayed 50. Read state does not recall emails or cancel queued delivery.",
  ], sources: ["src/components/account-notifications.tsx"] },
  { id: "support", title: "Support checks and limits of this guide", paragraphs: [
    "Identify the triggering action, trip, actor, intended recipient and expected channel. For dispatched actions inspect Actions & delivery batches, the evaluated audience, each channel status and skip/error reason. For database-triggered events inspect user_notifications and notification_email_queue instead; they need not have an action batch.",
    "Check preferences, active membership, presence suppression, saved webhook configuration, queue attempts/last_error and the external scheduler. Then trace Make and the downstream email provider. A prepared activity log or a configured template is not a delivery receipt.",
    "This guide describes code and migrations reviewed on 2 October 2026. It does not verify live migrations, enabled actions, saved templates, webhook destination, cron jobs or downstream provider settings. This documentation update sends no emails and changes no notification behaviour.",
  ], sources: ["src/app/backoffice/notifications/actions/page.tsx", "src/lib/notifications/dispatch.ts", "src/app/api/cron/notifications/route.ts"] },
];

export const notificationScenarios = [
  ["User expects a phone push alert", "Current push means an in-app inbox row. Device/browser push delivery is not implemented."],
  ["Password-reset email is missing", "Investigate Supabase Auth email delivery; the application webhook and preferences do not control it."],
  ["Stripe receipt or invoice email is missing", "Check Stripe’s configuration and delivery; this is separate from Journi application email."],
  ["Action is disabled or absent", "The dispatcher stops before creating a batch. Database-triggered paths are separate."],
  ["Template exists but no message arrives", "Confirm the event actually calls the dispatcher or another sender. Template configuration alone does not wire a trigger."],
  ["Activity log says prepared", "Prepared is not proof of dispatch, webhook handoff or inbox delivery."],
  ["User triggers an action themselves", "The dispatcher excludes matching actor user IDs. Database expense triggers do not apply that exclusion."],
  ["Recipient exists only as an email invite", "It may receive email/in-app rows by email; ID-based actor exclusion and presence suppression may not apply."],
  ["Same recipient has linked and email-only rows", "Deduplication keys differ; duplicate deliveries are possible."],
  ["Action targets invited_participant", "It can match multiple invited/linked/pending records, not necessarily only the latest invite."],
  ["Recipient disables email", "Email is skipped by preference checks; in-app can still be enabled."],
  ["Recipient disables in-app but keeps email", "Database expense/decision/reminder insertion can still queue email before suppressing the inbox row."],
  ["Recipient disables a category", "Both channels are gated for keys classified into that category; existing inbox items are not deleted."],
  ["Payment-labelled action ignores payments preference", "Check its key: payment.requested falls into planning; expense.* and reminder.payment* map to payments."],
  ["Preference lookup fails", "Immediate delivery is marked failed; queued delivery follows its retry policy rather than assuming permission."],
  ["User was recently active in another trip", "An action with suppression enabled can skip immediate email based on app-wide presence."],
  ["Queued email reaches an active user", "The queue worker does not use the action’s presence-suppression setting."],
  ["Webhook is not configured", "The sender throws; immediate delivery fails and queued delivery retries within its attempt limit."],
  ["Webhook returns 400, 500 or times out", "The handoff fails. Queue retries are separate from the immediate dispatcher’s one attempt."],
  ["Webhook returns success but no email appears", "Trace Make and the mail provider; HTTP success is only a handoff acknowledgement."],
  ["Make sends email but response is lost", "A queue retry can repeat the request. Make must honour Idempotency-Key to deduplicate it."],
  ["Global template changes but reminder styling does not", "Queued reminders use simple HTML rather than the global/custom template pipeline."],
  ["A linked template is disabled or its timing changes", "The dispatcher does not enforce those rule fields; action settings and the caller control delivery."],
  ["A custom action uses both email paths", "For expense.*, decision.* or reminder.*, an inbox insertion can queue email in addition to immediate email."],
  ["A split creates due payments", "Each assigned eligible payer receives a payment event; the expense trigger does not broadcast every share to the whole trip."],
  ["A payment is marked paid or returned to due", "The assigned eligible person and organiser are targeted, subject to preferences."],
  ["A traveller claims they paid or withdraws the claim", "The assigned person and organiser receive the claim-change event; this does not itself charge a card."],
  ["Payment save changes no tracked fields", "The trigger returns without creating another notification."],
  ["Payment is reassigned to another person", "The update targets the current payer; the old payer is not separately notified by that update."],
  ["A payment is deleted", "The removal event uses the old payment row’s eligible payer; removed/inactive travellers are excluded."],
  ["An expense transaction rolls back", "Notifications inserted by its transaction roll back too."],
  ["Payment is due tomorrow, today or three days overdue", "A reminder can be generated in those date buckets if due, unclaimed and otherwise eligible."],
  ["Payment is overdue by a different number of days", "There is no continuous daily overdue reminder schedule in this function."],
  ["Voting closes within 24 hours", "Eligible active participants with outstanding votes in undecided populated categories can receive one marker-deduplicated reminder."],
  ["Scheduler never calls the email worker", "Database reminders can exist in the inbox/queue without email delivery. pg_cron generation alone does not drain the queue."],
  ["Reminder cron runs twice", "Reminder markers prevent the same reminder being generated again for that key; queue claiming uses leases."],
  ["Recipient leaves or disables email while queued", "The worker rechecks eligibility and can skip the pending message."],
  ["Payment is paid or claimed before its reminder sends", "The queued payment reminder is skipped as stale."],
  ["Payment due date or voting deadline changes", "The queued reminder is skipped if its stored context no longer matches."],
  ["User votes after reminder generation", "The worker does not recheck outstanding votes; the email may still send if the deadline and other checks pass."],
  ["Worker fails five times", "The row becomes failed; this code does not automatically retry it indefinitely."],
  ["Worker stops during delivery", "Its ten-minute lease can expire and be reclaimed below the attempt cap; webhook deduplication remains necessary."],
  ["All deliveries were skipped", "A batch may still be completed with zero sent; inspect each delivery reason."],
  ["Two channels succeed for one recipient", "sent_count increases by two; it counts channel deliveries rather than unique people."],
  ["Unread count exceeds 50", "The count includes all accessible unread rows; the dropdown shows only the latest 50."],
  ["User opens a notification", "It is marked read, then a same-origin link can open; already-sent email is unaffected."],
  ["User marks all as read", "All accessible unread rows are updated, including rows outside the displayed 50."],
  ["New notification is not visible immediately", "The bell refreshes on opening/focus/visibility and polls every 30 seconds while visible."],
  ["Invite emails arrive twice", "Check both the dispatcher and the separate invite-response business webhook, plus any Make automation."],
];
